### ISSUE TITLE
reference_url rather than landing_page?

### ISSUE THREAD

**Issue by msdemlei** [gilleslandais/ivoa-dcp-data-origin#11]
I think the current landing_page item is identical to (or at least has a very substantial overlap) with what's called referenceURL in the Registry.  If that's true: Can't we use reference_url as a key just to not further inflate the number of different categories of URIs in the VO's metadata schemas?

If, on the other hand, there's a substantial different between landing_page and referenceURL, can we make that explicit in some place?

**Comment by gilleslandais** [comment]
I think they  both mean the same.
"referenceURL" is may be more ambiguous - but acceptable.
But if we update the term to be more compatible with VOResource, then I propose to remove the case sensitivity- what do you think of "reference_url"?

**Comment by msdemlei** [comment]
On Wed, Dec 13, 2023 at 01:58:28AM -0800, gilleslandais wrote:
> I think they  both mean the same.
> "referenceURL" is may be more ambiguous - but acceptable.
> But if we update the term to be more compatible with VOResource, then I propose to remove the case sensitivity- what do you think of "reference_url"?

Yeah, that would have been my choice, too.

**Comment by gilleslandais** [comment]
has been mofified in last push
