### ISSUE TITLE
Learn from HiPS meta-data

### ISSUE THREAD

**Issue by gilleslandais** [gilleslandais/ivoa-dcp-data-origin#2]
HiPS meta-data contains information that matches with Data-Orgin (https://www.ivoa.net/documents/HiPS/)
eg: hips_creator, hips_release_date, hips_copyright, obs_copyright, obs_copyright_url, bib_reference, prov_progenitor, etc.

**Comment by MihaelaBuga** [comment]
meta-data assigned to HiPS providing traceability to end-users:

- agent/center who created the HiPS and when : hips_creator, hips_release_date

- link with the original data : prov_progenitor, bib_reference , bib_reference_url , obs_copyright, obs_copyright_url, obs_ack

- transformations applied to the original data : hips_builder, hips_version, hipsgen_params , hips_order, hips_tile_width  

- understanding of the results : obs_description, t_min, t-max, obs-regime, em_min et em_max, dataproduct-type, hips_frame, ...

- reuse and citation : unique identifier : creator_did ,  hips_service_url , hips_copyright

We use the  associated metadata to query among all the HiPS, for example using Aladin filter option.

**Comment by augustfly** [comment]
From the HIPS IVOA doc... I'm not sure I understand these fields, either based on the example shown today or the HIPS doc...

| Keyword             | S/R | Description
|---------------------|-----|-------------------------------------------------
|obs_ack              |     | Acknowledgment mention.
|prov_progenitor (*)  | S   | Provenance of the original data – Format: free text
|bib_reference (*)    |     | Bibliographic reference
|bib_reference_url (*)|     |  URL to bibliographic reference
|obs_copyright        |     | Copyright mention associated to the original data – Format: free text
|obs_copyright_url    |     | URL to a copyright mention
|hips_copyright       |     | Copyright mention associated to the HiPS – Format: free text

My questions are:
- Is a DOI a valid URL from a FAIR persepctive for the obs_copyright_url?
- Is there a formal rec for how free text copyright values are written? I note that the Gaia example merged a bunch of DOI keys together -- creator, publisher. 
- If we are using URLs for bibligraphic references then must they be ADS URLs or could they be DOI urls? If many/all dataset DOIs are not in ADS then you'll find a need to use DOIs more often.

**Comment by MihaelaBuga** [comment]
Hello August Muench,

Thank you for your questions.

For the bibliographic reference URL, for the moment we are using both 
ADS URLs and the DOI urls. The HiPS standard for the bib_reference_url 
is not explicit in one way or another. If we may think to homogenize the 
URLs, we think put ADS URLs, as all the paper linked to our HiPS are in ADS.

As for the copyright, we do not have a rule for the free text copyright. 
With the Aladin team, we may consider creating DOIs for our HiPS.

Have a nice day,
Mihaela
