### ISSUE TITLE
Data licensing

### ISSUE THREAD

**Issue by augustfly** [gilleslandais/ivoa-dcp-data-origin#4]
During IVOA Fall 2022 Interop there was a discussion of the many ways licensing is unclear in data reuse, including:

- A data license should be discoverable and machine-actionable per the FAIR guidelines but this is infrequently the case;
- There are confounding issues over "Copyright", "License", and recommended best practices for attribution;
- There are confounding issues over blended objects with differing data rights;

We could discuss ways to make data rights (and licensing) information visible in DOI and IVO/Registry metadata and (b) if that information should be passed through Data Origin responses.

**Comment by gilleslandais** [comment]
About machine-actionable license: how to specify the licenses, with URI? which URI ?

Today, the <rights> metadata in Regsitry is a free text 
eg: vizier example.
https://dc.zah.uni-heidelberg.de/rr/q/pmh/pubreg.xml?verb=GetRecord&metadataPrefix=ivo_vor&identifier=ivo%3A%2F%2Fcds.vizier%2Fj%2Fapjs%2F241%2F37)

how to specify the <rights> metadata of the registry in accordance with the FAIR guideline?
